name: Update RSS

on:
  schedule:
    - cron: "*/10 * * * *"   # 每10分钟运行
  workflow_dispatch:         # 允许手动运行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉代码
        uses: actions/checkout@v3

      - name: 安装 Python 依赖
        run: |
          pip install requests

      - name: 运行脚本
        run: |
          python news.py

      - name: 提交更新
        run: |
          git config user.name "bot"
          git config user.email "bot@example.com"
          git add news.xml
          git commit -m "update news"
          git push
